project:
  type: website
  
website:
  title: "HUGOJIRA"
  favicon: favicon.png
  site-url: "https://hugojira.com/"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "huBlog"
        href: blog.qmd
      - text: "Proyectos"
        href: proyectos/index.qmd
      - icon: github
        href: https://github.com/hugojira/hublog
  page-footer: 
    left: "Sitio web hecho con [Quarto](https://quarto.org/), por Hugo Valenzuela Chaparro"
    center:
      - icon: linkedin
        href: https://www.linkedin.com/in/hugo-vach/
      - icon: github
        href: https://github.com/hugojira/
    right:
      - text: "Licencia: CC BY-SA 4.0"
        href: license.qmd
  comments:
    giscus:
      repo: hugojira/hublog
      language: es
format:
  html:
    theme: flatly
    css: styles.css
    from: "markdown+emoji"

editor: visual

